using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using GoPay.Common;
using KubirovackaAPI.Areas.Main.User.Models.Database;
using KubirovackaAPI.Areas.Main.User.Models.Database.Join;
using KubirovackaAPI.Areas.Payment.License.Enums;
using KubirovackaAPI.Areas.Report.Models.Database;

namespace KubirovackaAPI.Areas.Payment.License.Models.Database
{
    public class LicensePayment
    {
        public LicensePayment()
        {
        }
        
        [Required, Key]
        public long Id { get; set; } // GoPay generated
        [Required]
        public Guid OrderNumber { get; set; } // Generated by us
        [Required]
        public Guid CustomerId { get; set; }
        public User Customer { get; set; }
        [Required]
        public bool CompanyPurchase { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyStreetAndNumber { get; set; }
        public string CompanyZipCode { get; set; }
        public string CompanyCountry { get; set; }
        public string VatNum { get; set; } // ICO
        public string TaxId { get; set; } // DIC
        [Required] public LicensePaymentProvider Provider { get; set; } = LicensePaymentProvider.GoPay;
        public string? PurchaseId { get; set; } // GooglePlay or AppStore

        [Required, DisplayFormat(DataFormatString = "{0:dd. MMMM yyyy}", ApplyFormatInEditMode = true)]
        public DateTimeOffset OrderedAt { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd. MMMM yyyy}", ApplyFormatInEditMode = true)]
        public DateTimeOffset? PaidAt { get; set; }
        [Required]
        public Currency Currency { get; set; }
        [Required]
        public GoPay.Model.Payments.Payment.SessionState? State { get; set; }

        public IEnumerable<LicensePaymentItem> LicensePaymentItems { get; set; }

        public bool InvoiceGenerated { get; set; } = false;
        public bool InvoiceSent { get; set; } = false;

        public static LicensePayment CopyAsPaid(LicensePayment p, long id)
        {
            return new LicensePayment
            {
                Id = id,
                OrderNumber = Guid.NewGuid(),
                CustomerId = p.CustomerId,
                CompanyPurchase = p.CompanyPurchase,
                CompanyName = p.CompanyName,
                CompanyCity = p.CompanyCity,
                CompanyStreetAndNumber = p.CompanyStreetAndNumber,
                CompanyZipCode = p.CompanyZipCode,
                CompanyCountry = p.CompanyCountry,
                VatNum = p.VatNum,
                TaxId = p.TaxId,
                Provider = p.Provider,
                PurchaseId = p.PurchaseId,
                OrderedAt = DateTimeOffset.UtcNow,
                PaidAt = DateTimeOffset.UtcNow,
                Currency = p.Currency,
                State = GoPay.Model.Payments.Payment.SessionState.PAID,
                LicensePaymentItems = p.LicensePaymentItems.Select(e => LicensePaymentItem.Copy(e, id)).ToList(),
                InvoiceGenerated = false,
                InvoiceSent = false
            };
        }
    }
}