// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb99G4Ls5JFm9Z975QGmpNDAXaSoUCsxM',
    appId: '1:875831827696:web:ed6a2100a6ef8f2badf635',
    messagingSenderId: '875831827696',
    projectId: 'kubirovacka-one',
    authDomain: 'kubirovacka-one.firebaseapp.com',
    storageBucket: 'kubirovacka-one.appspot.com',
    measurementId: 'G-HGFEZZRYK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-XOPLr4VScADgGXWw-hSkBvEn3Ivf7Ig',
    appId: '1:875831827696:android:4fa9f21245f9b8ddadf635',
    messagingSenderId: '875831827696',
    projectId: 'kubirovacka-one',
    storageBucket: 'kubirovacka-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9FNFc0b-mMHhyqAqjP6JWcIbZZaix4M',
    appId: '1:875831827696:ios:ef545100a4a38dbbadf635',
    messagingSenderId: '875831827696',
    projectId: 'kubirovacka-one',
    storageBucket: 'kubirovacka-one.appspot.com',
    iosClientId: '875831827696-fqe5ego6tdt6on0v92jd0me4s0a8qmb9.apps.googleusercontent.com',
    iosBundleId: 'cz.kobrasoft.kubirovackaOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv9FNFc0b-mMHhyqAqjP6JWcIbZZaix4M',
    appId: '1:875831827696:ios:ef545100a4a38dbbadf635',
    messagingSenderId: '875831827696',
    projectId: 'kubirovacka-one',
    storageBucket: 'kubirovacka-one.appspot.com',
    iosClientId: '875831827696-fqe5ego6tdt6on0v92jd0me4s0a8qmb9.apps.googleusercontent.com',
    iosBundleId: 'cz.kobrasoft.kubirovackaOne',
  );
}
